apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-unsafe-app.fullname" . }}-config
data:
  app.conf: |
    mode=production
    admin_user={{ .Values.admin.user }}
    admin_pass={{ .Values.admin.password }} # sensitive data stored in ConfigMap (bad)