apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-unsafe-app.fullname" . }}
  annotations:
    # NOTE: No internal LB annotation -> will be public by default in many clouds
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "example-unsafe-app.name" . }}